@extends('frontend.main')

@section('title', 'Checkout')

@section('stylesheets')
    <style>
        
    </style>  
   

@endsection

@section('content')
<div class="container"><br><br><br><br><br>
<br><br>
	<h3 style="color:#1f3860;">Privacy Policy</h3>

	<p>
The Woolwich College website is an information system intended to present an integrated view of the College to prospective students, alumnae, the members of The Woolwich College, and others with an interest.<br><br>


<h5 style="color: #1f3860 ;">Site Usage Statistics</h5><br>

If you visit this site to view or download information, a standard log file will record:<br>

the name of the domain from which you access the Internet<br>
the date and time of your visit<br>
the page/s you visit<br>
your computing platform<br>
This data is used in the aggregate for purposes of analysing site traffic, managing the site, and providing accountability regarding the usefulness of our work.<br><br>

 

<h5 style="color: #1f3860 ;">Personal Data</h5>

Personal information about you is not gathered when you visit South London Academy website unless you choose to supply that information to us (for example, by filling out a form requesting information for a specific purpose).<br><br>

 

<h5 style="color: #1f3860 ;">Cookies</h5><br>

Your Internet browser has the in-built facility for storing small files (called “cookies”) that hold information which allows a website to recognise your account. Cookies enable us to identify your device, or you when you have logged in. We use cookies that are strictly necessary to enable you to move around the site or to provide certain basic features. We use cookies to enhance the functionality of the website by storing your preferences, for example. We also use cookies to help us to improve the performance of our website to provide you with a better user experience.<br><br>

 

We don’t sell the information collected by cookies, nor do we disclose the information to third parties, except where required by law (for example to government bodies and law enforcement agencies).<br><br>

 

<h5 style="color: #1f3860 ;">Google Analytics</h5><br>

This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies,” which are text files placed on your computer, to help the website analyse how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and Internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. Please refer to the Google Advertising Privacy Notice for more information about tracking cookies for Google Adwords & Google Analytics.<br><br>

 

<h5 style="color: #1f3860 ;">Google Adwords Conversion Tracking</h5><br>

We use Google Adwords Conversion tracker which uses cookies to help us determine how many people who clicked on our Google Ads end up contacting us through the website. This tracking cookie is set on your browser only when you click on a Google Ad and these cookies help us increase the website’s effectiveness for our visitors. These cookies expire within 30 days and do not contain information that can identify you personally. Please refer to the Google Advertising Privacy Notice for more information about Google Conversion Tracking and the ability to opt out.<br>

 

<h5 style="color: #1f3860 ;">Google AdWords Remarketing</h5><br>

We use Google AdWords Remarketing which uses cookies to help us deliver targeted online adverts based on past visits to our website. Google uses this information to carefully display South London Academy adverts on various third party websites across the internet. These cookies are set to expire and do not contain information that can identify you personally. Please refer to the Google Advertising Privacy Notice for more information about the ability to opt out.<br><br>

 

<h5 style="color: #1f3860 ;">Disclosure to Third Parties</h5>

Personal information collected on this website is not disclosed to third parties unless the third party is an institutionally-authorized provider of services to the College. Users of these services are subject to the privacy policies established by the third-party provider. One such third-party provider of services is Google, Inc., whose Google Analytics product is used to analyse website traffic in the aggregate so that we can make the site more useful to you.<br><br>

  

<h5 style="color: #1f3860 ;">Links to Other Sites</h5>

The College web site contains links to many sites which are beyond our control. South London Academy is not responsible for the privacy practices or content of these other sites.<br><br>

   

<h5 style="color: #1f3860 ;">How Does The Woolwich College Protect the Privacy of Children Younger Than 13 Years?</h5><br>

The Woolwich College is concerned about the privacy of young children and does not knowingly collect any personal information from children under 13 years. We suggest that you become involved with your child's access to the Internet and to our site to ensure that his or her privacy is well protected.<br><br>

 

<h5 style="color: #1f3860 ;">Your Consent</h5><br>

If we decide to make changes to our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.<br><br>

 

<h5 style="color: #1f3860 ;">If you have any questions about this privacy policy</h5><br>

If you have any questions about this privacy policy, or the content or practices of our website, you can contact The Woolwich College:<br>

Postal Address: 2nd Floor, Barnard Close, Woolwich, London SE18 6DD United Kingdom<br>

Phone: 020 8305 8700<br>

Email id: admissions@thewoolwichcollege.org.uk<br><br>

<h5 style="color: #1f3860 ;">Data Protection Policy</h5><br>
The Academy needs to keep certain information about employees, students, and other individuals in order to perform its business duties.

 <br>

SLA's core purpose is to transform the lives of our students, through working with them and with our many partners to provide education, opportunity and positive outcomes.</p>
<br>
 



</div>

@endsection